// SPDX-FileCopyrightText: 2024 The OpenSn Authors <https://open-sn.github.io/opensn/>
// SPDX-License-Identifier: MIT

#include "modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/angle_set/cbc_angle_set.h"
#include "modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/communicators/cbc_async_comm.h"
#include "modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/spds/cbc.h"
#include "modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep_chunks/sweep_chunk.h"
#include "framework/mesh/mesh_continuum/mesh_continuum.h"
#include "framework/math/math_range.h"
#include "framework/logging/log.h"
#include "framework/runtime.h"
#include "caliper/cali.h"

namespace opensn
{

CBC_AngleSet::CBC_AngleSet(size_t id,
                           size_t num_groups,
                           const SPDS& spds,
                           std::shared_ptr<FLUDS>& fluds,
                           const std::vector<size_t>& angle_indices,
                           std::map<uint64_t, std::shared_ptr<SweepBoundary>>& boundaries,
                           const MPICommunicatorSet& comm_set)
  : AngleSet(id, num_groups, spds, fluds, angle_indices, boundaries),
    cbc_spds_(dynamic_cast<const CBC_SPDS&>(spds_)),
    async_comm_(id, *fluds, comm_set)
{
  // Populate map in constructor
  for (unsigned int local_idx = 0; local_idx < angles_.size(); ++local_idx) // angles_ is from base AngleSet
  {
    global_to_local_angle_map_[angles_[local_idx]] = local_idx;
  }
}

AsynchronousCommunicator*
CBC_AngleSet::GetCommunicator()
{
  return static_cast<AsynchronousCommunicator*>(&async_comm_);
}

AngleSetStatus
CBC_AngleSet::AngleSetAdvance(SweepChunk& sweep_chunk, AngleSetStatus permission)
{
  CALI_CXX_MARK_SCOPE("CBC_AngleSet::AngleSetAdvance");

  if (executed_)
    return AngleSetStatus::FINISHED;

  if (current_task_list_.empty())
  {
    current_task_list_ = cbc_spds_.GetTaskList();
  }

  sweep_chunk.SetAngleSet(*this);

  auto tasks_who_received_data = async_comm_.ReceiveData();

  for (const uint64_t task_number : tasks_who_received_data)
    --current_task_list_[task_number].num_dependencies;

  async_comm_.SendData();

  // Check if boundaries allow for execution
  for (auto& [bid, boundary] : boundaries_)
    if (not boundary->CheckAnglesReadyStatus(angles_))
      return AngleSetStatus::NOT_FINISHED;

  /*
  bool all_tasks_completed = true;
  bool a_task_executed = true;
  while (a_task_executed)
  {
    a_task_executed = false;
    for (auto& cell_task : current_task_list_)
    {
      if (not cell_task.completed)
        all_tasks_completed = false;
      if (cell_task.num_dependencies == 0 and not cell_task.completed)
      {
        const Cell* cell_ptr = cell_task.cell_ptr;

        sweep_chunk.SetCell(cell_ptr, *this); // *this is the current CBC_AngleSet
        sweep_chunk.Sweep(*this);

        for (uint64_t local_task_num : cell_task.successors)
          --current_task_list_[local_task_num].num_dependencies;

        cell_task.completed = true;
        a_task_executed = true;
        async_comm_.SendData();
      }
    } // for cell_task
    async_comm_.SendData();
  }

  const bool all_messages_sent = async_comm_.SendData();

  if (all_tasks_completed and all_messages_sent)
  {
    // Update boundary readiness
    for (auto& [bid, boundary] : boundaries_)
      boundary->UpdateAnglesReadyStatus(angles_);
    executed_ = true;
    return AngleSetStatus::FINISHED;
  }

  return AngleSetStatus::NOT_FINISHED;
*/

  // /*
  bool at_least_one_task_executed_in_a_pass;
  do
  {
      at_least_one_task_executed_in_a_pass = false;
      for (auto& cell_task : current_task_list_)
      {
          if (cell_task.num_dependencies == 0 && !cell_task.completed)
          {
              const Cell* cell_ptr = cell_task.cell_ptr;
              sweep_chunk.SetCell(cell_ptr, *this);
              sweep_chunk.Sweep(*this);

              for (uint64_t local_task_num : cell_task.successors)
              {
                  if (local_task_num < current_task_list_.size())
                      --current_task_list_[local_task_num].num_dependencies;
                  // else { error }
              }
              cell_task.completed = true;
              at_least_one_task_executed_in_a_pass = true;
              async_comm_.SendData(); // Send data generated by this cell
          }
      }
      if (at_least_one_task_executed_in_a_pass)
      {
          async_comm_.SendData(); // Consolidate sends after a pass with executions
      }
  } while (at_least_one_task_executed_in_a_pass); // Keep looping if progress was made

  // After the loop, check if ALL tasks are now complete
  bool all_local_tasks_truly_completed = true;
  for (const auto& cell_task : current_task_list_)
  {
      if (!cell_task.completed)
      {
          all_local_tasks_truly_completed = false;
          break;
      }
  }

  const bool all_mpi_messages_sent = async_comm_.SendData(); // Final flush

  if (all_local_tasks_truly_completed && all_mpi_messages_sent)
  {
      for (auto& [bid, boundary] : boundaries_)
          boundary->UpdateAnglesReadyStatus(angles_);
      executed_ = true;
      return AngleSetStatus::FINISHED;
  }

  return AngleSetStatus::NOT_FINISHED;
  // */
}

void
CBC_AngleSet::ResetSweepBuffers()
{
  current_task_list_.clear();
  async_comm_.Reset();
  fluds_->ClearLocalAndReceivePsi();
  executed_ = false;
}

const double*
CBC_AngleSet::PsiBoundary(uint64_t boundary_id,
                          unsigned int angle_num,
                          uint64_t cell_local_id,
                          unsigned int face_num,
                          unsigned int fi,
                          int g,
                          bool surface_source_active)
{
  if (boundaries_[boundary_id]->IsReflecting())
    return boundaries_[boundary_id]->PsiIncoming(cell_local_id, face_num, fi, angle_num, g);

  if (not surface_source_active)
    return boundaries_[boundary_id]->ZeroFlux(g);

  return boundaries_[boundary_id]->PsiIncoming(cell_local_id, face_num, fi, angle_num, g);
}

double*
CBC_AngleSet::PsiReflected(uint64_t boundary_id,
                           unsigned int angle_num,
                           uint64_t cell_local_id,
                           unsigned int face_num,
                           unsigned int fi)
{
  return boundaries_[boundary_id]->PsiOutgoing(cell_local_id, face_num, fi, angle_num);
}

unsigned int
CBC_AngleSet::GetLocalAngleIndex(size_t global_direction_num) const
{
  auto it = global_to_local_angle_map_.find(global_direction_num);
  if (it == global_to_local_angle_map_.end()) {
    throw std::out_of_range("CBC_AngleSet: Global angle index " +
                            std::to_string(global_direction_num) +
                            " not found in this AngleSet. Current AngleSet ID: " + std::to_string(id_));
  }
  return it->second;
}

} // namespace opensn
