#!/bin/zsh

set -euo pipefail

script=${0:A}
source_dir=${OPENSN_SOURCE:-${script:h:h:h:h}}
study_root=${OPENSN_TUO_STUDY_ROOT:-/usr/workspace/${USER}/opensn-gpu/cbcd-v2-studies}
work_root=${OPENSN_TUO_ROOT:-$study_root/builds/gfx942-update-3}
build_dir=${OPENSN_TUO_BUILD:-$work_root/build-opensn}
environment=$work_root/env.zsh
binary=$build_dir/python/opensn
mesh_dir=${OPENSN_TUO_MESH_DIR:-$study_root/builds/gfx942/mesh-cache}
results_root=${OPENSN_TUO_RESULTS:-$study_root/results}
label=${OPENSN_TUO_LABEL:-update-3}
interactive_root=${OPENSN_TUO_INTERACTIVE_ROOT:-$results_root/$label-interactive}
batch_root=${OPENSN_TUO_BATCH_ROOT:-$results_root/$label-batch}
profile_root=${OPENSN_TUO_PROFILE_ROOT:-$results_root/$label-profile/resource-aware}
hardware_interactive=$interactive_root/hardware
resource_interactive=$interactive_root/resource-aware
hardware_batch=$batch_root/hardware
resource_batch=$batch_root/resource-aware
queue=${OPENSN_TUO_QUEUE:-pdebug}
interactive_time=${OPENSN_TUO_TIME_LIMIT:-60m}
interactive_iterations=${OPENSN_TUO_INTERACTIVE_ITERATIONS:-10}
batch_nodes=${OPENSN_TUO_NODES:-1,2,4,8,16,32,64,128,256}
batch_repetitions=${OPENSN_TUO_REPETITIONS:-3}
batch_iterations=${OPENSN_TUO_MAX_ITERATIONS:-10}
batch_time=${OPENSN_TUO_BATCH_TIME_LIMIT:-4h}
profile_nodes=${OPENSN_TUO_PROFILE_NODES:-1,2,4}
profile_names=${OPENSN_TUO_PROFILES:-baseline,caliper,caliper-mpi,pmpi}
profile_kinds=${OPENSN_TUO_PROFILE_KINDS:-strong}
profile_divisor=${OPENSN_TUO_PROFILE_DIVISOR:-39}
profile_iterations=${OPENSN_TUO_PROFILE_ITERATIONS:-10}
profile_time=${OPENSN_TUO_PROFILE_TIME_LIMIT:-6h}
progress_interval=${OPENSN_TUO_PROGRESS_INTERVAL:-60}
bank=${OPENSN_TUO_BANK:-}
worker_count=${OPENSN_CBCD_NUM_WORKERS:-}

usage()
{
  cat >&2 <<EOF
usage: $0 COMMAND [ARGS]

Commands:
  build                         fresh/resumable one-node Tuo build
  build-here                    build in the current allocation
  rebuild                       rebuild OpenSn after pulling source changes
  rebuild-here                  rebuild OpenSn in the current allocation
  prepare-interactive [POLICY]  prepare one or both 1/2/4-node policy studies
  run-interactive [POLICY]      run one or both policies in one allocation
  run-interactive-here [POLICY] run one or both policies in the current allocation
  run POLICY NODES              run one policy at 1, 2, 4, or 8 nodes
  run-here POLICY NODES         run one policy in the current allocation
  collect-interactive [POLICY]  collect one study or compare both studies
  prepare-batch [POLICY]        prepare one or both strong/weak pbatch studies
  submit-batch [POLICY]         submit one or both pbatch studies
  collect-batch [POLICY]        collect one study or compare both studies
  prepare-profile               prepare resource-aware profiling jobs
  submit-profile                submit resource-aware profiling jobs
  run-profile-interactive [P]   run profile P, or every selected profile, via pdebug
  resume-profile-interactive [P]
                                run only incomplete cases and continue after failures
  run-profile-interactive-here P [NODES]
                                run profile P in the current allocation; optionally select nodes
  collect-profile               collect the resource-aware profiling inventory
  paths                         print selected paths and study settings

POLICY is hardware or resource-aware. The default mesh directory reuses the
plain cube-dN.msh files produced by the older Tuo framework. Override it with
OPENSN_TUO_MESH_DIR. No mesh is generated by this helper.
EOF
  exit 2
}

check_policy()
{
  case $1 in
    hardware|resource-aware) ;;
    *) print -u2 'POLICY must be hardware or resource-aware.'; exit 2 ;;
  esac
}

check_nodes()
{
  case $1 in
    1|2|4|8) ;;
    *) print -u2 'NODES must be 1, 2, 4, or 8.'; exit 2 ;;
  esac
}

check_profile()
{
  case $1 in
    baseline|cbcd-metrics|caliper|caliper-mpi|pmpi|caliper-rocm|rocprof|hpctoolkit|omniperf) ;;
    *) print -u2 "Unknown profile: $1"; exit 2 ;;
  esac
}

check_settings()
{
  [[ $interactive_iterations == <1-> ]] || {
    print -u2 'OPENSN_TUO_INTERACTIVE_ITERATIONS must be positive.'
    exit 2
  }
  [[ $batch_repetitions == <1-> && $batch_iterations == <1-> ]] || {
    print -u2 'Batch repetitions and iterations must be positive.'
    exit 2
  }
  [[ $profile_divisor == <1-> && $profile_iterations == <1-> ]] || {
    print -u2 'Profile divisor and iteration count must be positive.'
    exit 2
  }
  [[ $progress_interval == <0-> ]] || {
    print -u2 'OPENSN_TUO_PROGRESS_INTERVAL must be a nonnegative number of seconds.'
    exit 2
  }
  [[ -z $worker_count || $worker_count == <1-> ]] || {
    print -u2 'OPENSN_CBCD_NUM_WORKERS must be positive when set.'
    exit 2
  }
  [[ $queue == pdebug ]] || {
    print -u2 'Interactive commands are restricted to the pdebug queue.'
    exit 2
  }
}

require_build()
{
  [[ -r $environment && -x $binary ]] || {
    print -u2 "OpenSn is not ready under $work_root"
    print -u2 "Run '$script build' first."
    exit 1
  }
}

allocation()
{
  local nodes=$1
  local ranks=$((nodes * 4))
  local -a command=(
    flux alloc -N "$nodes" -n "$ranks" -q pdebug
    --exclusive -t "$interactive_time"
  )
  [[ -z $bank ]] || command+=(-B "$bank")
  print -r -l -- "${command[@]}"
}

print_latest_progress()
{
  local result_root=$1
  local stdout_path stderr_path
  stdout_path=$(
    { find "$result_root" -type f -name stdout.txt -printf '%T@ %p\n' 2>/dev/null || true } |
      sort -nr |
      head -n 1 |
      cut -d' ' -f2-
  )
  [[ -n $stdout_path ]] || {
    print -- "  no stdout file was produced under $result_root"
    return
  }

  print -- "  output=$stdout_path"
  grep -E \
    'CBCD scheduler|WGS groups .*iteration|WGS groups .*final|avg_sweep_time|unknowns =|OPENSN_TUO_SCALAR_FLUX_MAX|OpenSn finished' \
    "$stdout_path" | tail -n 20 || true
  stderr_path=${stdout_path:h}/stderr.txt
  if [[ -s $stderr_path ]]; then
    print -- '  latest stderr:'
    tail -n 20 "$stderr_path"
  fi
}

monitor_generated_job()
{
  local job_pid=$1
  local result_root=$2
  local stdout_path latest_line previous_line=''

  while kill -0 "$job_pid" 2>/dev/null; do
    sleep "$progress_interval"
    kill -0 "$job_pid" 2>/dev/null || break
    stdout_path=$(
      { find "$result_root" -type f -name stdout.txt -printf '%T@ %p\n' 2>/dev/null || true } |
        sort -nr |
        head -n 1 |
        cut -d' ' -f2-
    )
    if [[ -z $stdout_path ]]; then
      print -- "[$(date '+%Y-%m-%d %H:%M:%S')] still running; output directory is being created"
      continue
    fi
    latest_line=$(
      grep -E \
        'CBCD scheduler|CBCD communication summary|WGS groups .*iteration|WGS groups .*final|avg_sweep_time|unknowns =|OPENSN_TUO_SCALAR_FLUX_MAX|OpenSn finished' \
        "$stdout_path" | tail -n 1 || true
    )
    if [[ -n $latest_line && $latest_line != $previous_line ]]; then
      print -- "[$(date '+%Y-%m-%d %H:%M:%S')] progress: $latest_line"
      previous_line=$latest_line
    else
      print -- "[$(date '+%Y-%m-%d %H:%M:%S')] still running; output=$stdout_path"
    fi
  done
}

run_generated_job()
{
  local description=$1
  local job=$2
  local result_root=$3
  local job_rc job_pid monitor_pid=0

  print -- "[$(date '+%Y-%m-%d %H:%M:%S')] $description started"
  print -- "  job=$job"
  set +e
  zsh "$job" &
  job_pid=$!
  if (( progress_interval > 0 )); then
    monitor_generated_job "$job_pid" "$result_root" &
    monitor_pid=$!
  fi
  wait "$job_pid"
  job_rc=$?
  if (( monitor_pid > 0 )); then
    kill "$monitor_pid" 2>/dev/null
    wait "$monitor_pid" 2>/dev/null
  fi
  set -e
  print_latest_progress "$result_root"
  if (( job_rc != 0 )); then
    print -u2 -- "[$(date '+%Y-%m-%d %H:%M:%S')] $description failed (rc=$job_rc)"
    return $job_rc
  fi
  print -- "[$(date '+%Y-%m-%d %H:%M:%S')] $description completed"
}

build_here()
{
  if [[ -r $environment && -x $binary ]]; then
    print -- "Reusing completed build: $binary"
    return
  fi

  export OPENSN_SOURCE=$source_dir
  export OPENSN_TUO_ROOT=$work_root
  export OPENSN_TUO_BUILD=$build_dir
  mkdir -p -- "$work_root/logs"

  zsh "$source_dir/tools/scaling/tuo/bootstrap.zsh" all \
    |& tee "$work_root/logs/build.log"
}

build()
{
  if [[ -r $environment && -x $binary ]]; then
    print -- "Reusing completed build: $binary"
    return
  fi
  local -a command=("${(@f)$(allocation 1)}")
  "$command[@]" zsh "$script" build-here
}

rebuild_here()
{
  [[ -r $environment ]] || {
    print -u2 "The dependency environment is not ready under $work_root"
    print -u2 "Run '$script build' first."
    exit 1
  }

  export OPENSN_SOURCE=$source_dir
  export OPENSN_TUO_ROOT=$work_root
  export OPENSN_TUO_BUILD=$build_dir
  mkdir -p -- "$work_root/logs"
  zsh "$source_dir/tools/scaling/tuo/bootstrap.zsh" build-opensn \
    |& tee "$work_root/logs/rebuild-opensn.log"
}

rebuild()
{
  local -a command=("${(@f)$(allocation 1)}")
  "$command[@]" zsh "$script" rebuild-here
}

study_for()
{
  local scope=$1
  local policy=$2
  case $scope:$policy in
    interactive:hardware) print -- "$hardware_interactive" ;;
    interactive:resource-aware) print -- "$resource_interactive" ;;
    batch:hardware) print -- "$hardware_batch" ;;
    batch:resource-aware) print -- "$resource_batch" ;;
    *) exit 2 ;;
  esac
}

prepare_one()
{
  local scope=$1
  local policy=$2
  local output=$(study_for "$scope" "$policy")

  local nodes kinds repetitions iterations study_queue time_limit
  if [[ $scope == interactive ]]; then
    nodes=1,2,4
    kinds=strong
    repetitions=1
    iterations=$interactive_iterations
    study_queue=pdebug
    time_limit=$interactive_time
  else
    nodes=$batch_nodes
    kinds=strong,weak
    repetitions=$batch_repetitions
    iterations=$batch_iterations
    study_queue=pbatch
    time_limit=$batch_time
  fi

  local -a optional_args=()
  [[ -z $bank ]] || optional_args+=(--bank "$bank")
  [[ -z $worker_count ]] || optional_args+=(--cbcd-workers "$worker_count")

  source "$environment"
  python "$source_dir/tools/scaling/tuo/study.py" prepare \
    --binary "$binary" \
    --environment "$environment" \
    --output "$output" \
    --mesh-dir "$mesh_dir" \
    --label "$label-$scope-$policy" \
    --nodes "$nodes" \
    --kinds "$kinds" \
    --repetitions "$repetitions" \
    --max-iterations "$iterations" \
    --queue "$study_queue" \
    --time-limit "$time_limit" \
    --refresh \
    --worker-policy "$policy" \
    --no-save-angular-flux \
    "${optional_args[@]}"
}

prepare_interactive()
{
  require_build
  if (( $# == 1 )); then
    check_policy "$1"
    prepare_one interactive "$1"
  else
    prepare_one interactive hardware
    prepare_one interactive resource-aware
  fi
}

run_here()
{
  local policy=$1
  local nodes=$2
  check_policy "$policy"
  check_nodes "$nodes"
  local study=$(study_for interactive "$policy")
  [[ -x $study/jobs/strong-$nodes.zsh ]] || {
    print -u2 'Run prepare-interactive first.'
    exit 1
  }
  run_generated_job \
    "policy=$policy nodes=$nodes" \
    "$study/jobs/strong-$nodes.zsh" \
    "$study/results/strong/nodes-$nodes"
}

run_one()
{
  local policy=$1
  local nodes=$2
  check_policy "$policy"
  check_nodes "$nodes"
  local -a command=("${(@f)$(allocation "$nodes")}")
  "$command[@]" zsh "$script" run-here "$policy" "$nodes"
}

run_interactive_here()
{
  if (( $# == 1 )); then
    check_policy "$1"
    run_here "$1" 1
    run_here "$1" 2
    run_here "$1" 4
    return
  fi
  run_here hardware 1
  run_here resource-aware 1
  run_here resource-aware 2
  run_here hardware 2
  run_here hardware 4
  run_here resource-aware 4
}

run_interactive()
{
  prepare_interactive "$@"
  local -a command=("${(@f)$(allocation 4)}")
  "$command[@]" zsh "$script" run-interactive-here "$@"
}

collect_one()
{
  local study=$1
  source "$environment"
  python "$source_dir/tools/scaling/tuo/study.py" collect --study "$study"
  sed -n '1,40p' "$study/summary.md"
}

compare_pair()
{
  local scope=$1
  local hardware=$(study_for "$scope" hardware)
  local resource=$(study_for "$scope" resource-aware)
  local output
  if [[ $scope == interactive ]]; then
    output=$interactive_root/comparison
  else
    output=$batch_root/comparison
  fi
  source "$environment"
  python "$source_dir/tools/scaling/tuo/study.py" compare \
    --baseline "$hardware" \
    --candidate "$resource" \
    --output "$output"
  sed -n '1,80p' "$output/comparison.md"
}

collect_interactive()
{
  require_build
  if (( $# == 1 )); then
    check_policy "$1"
    collect_one "$(study_for interactive "$1")"
    return
  fi
  collect_one "$hardware_interactive"
  collect_one "$resource_interactive"
  compare_pair interactive
}

prepare_batch()
{
  require_build
  if (( $# == 1 )); then
    check_policy "$1"
    prepare_one batch "$1"
    return
  fi
  prepare_one batch hardware
  prepare_one batch resource-aware
}

submit_batch()
{
  prepare_batch "$@"
  if (( $# == 1 )); then
    zsh "$(study_for batch "$1")/submit.zsh"
    return
  fi
  zsh "$hardware_batch/submit.zsh"
  zsh "$resource_batch/submit.zsh"
}

collect_batch()
{
  require_build
  if (( $# == 1 )); then
    check_policy "$1"
    collect_one "$(study_for batch "$1")"
    return
  fi
  collect_one "$hardware_batch"
  collect_one "$resource_batch"
  compare_pair batch
}

prepare_profile_for()
{
  local study_queue=$1
  local time_limit=$profile_time
  [[ $study_queue == pdebug ]] && time_limit=$interactive_time
  require_build
  local -a optional_args=()
  [[ -z $bank ]] || optional_args+=(--bank "$bank")
  [[ -z $worker_count ]] || optional_args+=(--cbcd-workers "$worker_count")

  source "$environment"
  python "$source_dir/tools/scaling/tuo/study.py" prepare-profile \
    --binary "$binary" \
    --environment "$environment" \
    --output "$profile_root" \
    --mesh-dir "$mesh_dir" \
    --label "$label-profile-resource-aware" \
    --profile-divisor "$profile_divisor" \
    --profile-nodes "$profile_nodes" \
    --profile-kinds "$profile_kinds" \
    --profiles "$profile_names" \
    --max-iterations "$profile_iterations" \
    --worker-policy resource-aware \
    --queue "$study_queue" \
    --time-limit "$time_limit" \
    --refresh \
    --no-save-angular-flux \
    "${optional_args[@]}"
}


prepare_profile()
{
  prepare_profile_for pbatch
}

submit_profile()
{
  prepare_profile
  zsh "$profile_root/submit.zsh" --nodes "$profile_nodes" --profiles "$profile_names"
}

run_profile_interactive_here()
{
  local profile=$1
  local selected_nodes=${2:-$profile_nodes}
  check_profile "$profile"
  local ran=0
  local kind nodes job
  for kind in ${(s:,:)profile_kinds}; do
    for nodes in ${(s:,:)selected_nodes}; do
      check_nodes "$nodes"
      job=$profile_root/jobs/$profile-$kind-$nodes.zsh
      [[ -x $job ]] || continue
      run_generated_job \
        "profile=$profile kind=$kind nodes=$nodes" \
        "$job" \
        "$profile_root/results/$profile/$kind/nodes-$nodes"
      ran=1
    done
  done
  (( ran == 1 )) || {
    print -u2 "No generated jobs selected for profile '$profile'."
    exit 1
  }
}

profile_case_complete()
{
  local profile=$1
  local kind=$2
  local nodes=$3
  local root=$profile_root/results/$profile/$kind/nodes-$nodes
  local run
  for run in "$root"/run-*(N/); do
    if [[ -f $run/SUCCESS && -r $run/exit_code.txt && $(<"$run/exit_code.txt") == 0 ]]; then
      return 0
    fi
  done
  return 1
}

run_profile_interactive()
{
  require_build
  (( $# <= 1 )) || usage
  prepare_profile_for pdebug

  local -a selected_profiles
  if (( $# == 1 )); then
    check_profile "$1"
    selected_profiles=("$1")
  else
    selected_profiles=("${(@s:,:)profile_names}")
  fi

  local profile kind nodes max_nodes job
  for profile in "${selected_profiles[@]}"; do
    check_profile "$profile"
    max_nodes=0
    for kind in ${(s:,:)profile_kinds}; do
      for nodes in ${(s:,:)profile_nodes}; do
        check_nodes "$nodes"
        job=$profile_root/jobs/$profile-$kind-$nodes.zsh
        [[ -x $job ]] || continue
        (( nodes > max_nodes )) && max_nodes=$nodes
      done
    done
    (( max_nodes > 0 )) || {
      print -u2 "No generated jobs selected for profile '$profile'."
      exit 1
    }

    print -- "[$(date '+%Y-%m-%d %H:%M:%S')] requesting $max_nodes pdebug node(s) for $profile"
    local -a command=("${(@f)$(allocation "$max_nodes")}")
    "$command[@]" zsh "$script" run-profile-interactive-here "$profile"
  done
}

resume_profile_interactive()
{
  require_build
  (( $# <= 1 )) || usage
  if [[ -r $profile_root/manifest.json ]]; then
    print -- "Reusing prepared profile study: $profile_root"
  else
    prepare_profile_for pdebug
  fi

  local -a selected_profiles
  if (( $# == 1 )); then
    check_profile "$1"
    selected_profiles=("$1")
  else
    selected_profiles=("${(@s:,:)profile_names}")
  fi

  local overall_rc=0
  local profile kind nodes max_nodes selected_nodes
  local -a incomplete_nodes command
  for profile in "${selected_profiles[@]}"; do
    incomplete_nodes=()
    max_nodes=0
    for nodes in ${(s:,:)profile_nodes}; do
      check_nodes "$nodes"
      local node_complete=1
      for kind in ${(s:,:)profile_kinds}; do
        [[ -x $profile_root/jobs/$profile-$kind-$nodes.zsh ]] || continue
        if profile_case_complete "$profile" "$kind" "$nodes"; then
          print -- "[$(date '+%Y-%m-%d %H:%M:%S')] profile=$profile kind=$kind nodes=$nodes already complete"
        else
          node_complete=0
        fi
      done
      (( node_complete == 1 )) && continue
      incomplete_nodes+=("$nodes")
      (( nodes > max_nodes )) && max_nodes=$nodes
    done
    if (( ${#incomplete_nodes} == 0 )); then
      print -- "[$(date '+%Y-%m-%d %H:%M:%S')] profile=$profile has no incomplete cases"
      continue
    fi

    selected_nodes=${(j:,:)incomplete_nodes}
    print -- "[$(date '+%Y-%m-%d %H:%M:%S')] requesting $max_nodes pdebug node(s) for profile=$profile nodes=$selected_nodes"
    command=("${(@f)$(allocation "$max_nodes")}")
    if ! "$command[@]" zsh "$script" run-profile-interactive-here "$profile" "$selected_nodes"; then
      print -u2 -- "[$(date '+%Y-%m-%d %H:%M:%S')] profile=$profile remains incomplete"
      overall_rc=1
    fi
  done
  return $overall_rc
}

collect_profile()
{
  require_build
  source "$environment"
  python "$source_dir/tools/scaling/tuo/study.py" collect-profile --study "$profile_root"
  sed -n '1,80p' "$profile_root/profile-summary.md"
  [[ ! -r $profile_root/cbcd-metrics-summary.md ]] ||
    sed -n '1,80p' "$profile_root/cbcd-metrics-summary.md"
}

paths()
{
  print -- "source=$source_dir"
  print -- "root=$work_root"
  print -- "environment=$environment"
  print -- "build=$build_dir"
  print -- "binary=$binary"
  print -- "meshes=$mesh_dir"
  print -- "interactive_hardware=$hardware_interactive"
  print -- "interactive_resource_aware=$resource_interactive"
  print -- "batch_hardware=$hardware_batch"
  print -- "batch_resource_aware=$resource_batch"
  print -- "profile_resource_aware=$profile_root"
  print -- "interactive_iterations=$interactive_iterations"
  print -- "batch_nodes=$batch_nodes"
  print -- "batch_repetitions=$batch_repetitions"
  print -- "batch_iterations=$batch_iterations"
  print -- "batch_time_limit=$batch_time"
  print -- "profile_nodes=$profile_nodes"
  print -- "profile_kinds=$profile_kinds"
  print -- "profiles=$profile_names"
  print -- "profile_divisor=$profile_divisor"
  print -- "profile_iterations=$profile_iterations"
  print -- "profile_time_limit=$profile_time"
  print -- "progress_interval_seconds=$progress_interval"
  print -- "fixed_workers=${worker_count:-unset}"
}

check_settings
(( $# >= 1 )) || usage
command=$1
shift
case $command in
  build) (( $# == 0 )) || usage; build ;;
  build-here) (( $# == 0 )) || usage; build_here ;;
  rebuild) (( $# == 0 )) || usage; rebuild ;;
  rebuild-here) (( $# == 0 )) || usage; rebuild_here ;;
  prepare-interactive) (( $# <= 1 )) || usage; prepare_interactive "$@" ;;
  run-interactive) (( $# <= 1 )) || usage; run_interactive "$@" ;;
  run-interactive-here) (( $# <= 1 )) || usage; run_interactive_here "$@" ;;
  run) (( $# == 2 )) || usage; run_one "$1" "$2" ;;
  run-here) (( $# == 2 )) || usage; run_here "$1" "$2" ;;
  collect-interactive) (( $# <= 1 )) || usage; collect_interactive "$@" ;;
  prepare-batch) (( $# <= 1 )) || usage; prepare_batch "$@" ;;
  submit-batch) (( $# <= 1 )) || usage; submit_batch "$@" ;;
  collect-batch) (( $# <= 1 )) || usage; collect_batch "$@" ;;
  prepare-profile) (( $# == 0 )) || usage; prepare_profile ;;
  submit-profile) (( $# == 0 )) || usage; submit_profile ;;
  run-profile-interactive) (( $# <= 1 )) || usage; run_profile_interactive "$@" ;;
  resume-profile-interactive) (( $# <= 1 )) || usage; resume_profile_interactive "$@" ;;
  run-profile-interactive-here) (( $# >= 1 && $# <= 2 )) || usage; run_profile_interactive_here "$@" ;;
  collect-profile) (( $# == 0 )) || usage; collect_profile ;;
  paths) (( $# == 0 )) || usage; paths ;;
  *) usage ;;
esac
