#!/bin/zsh

set -euo pipefail

script=${0:A}
source_dir=${OPENSN_SOURCE:-${script:h:h:h:h}}
study_root=${OPENSN_TUO_STUDY_ROOT:-/usr/workspace/${USER}/opensn-gpu/cbcd-v2-studies}
work_root=${OPENSN_TUO_ROOT:-$study_root/builds/gfx942-update-3}
build_dir=${OPENSN_TUO_BUILD:-$work_root/build-opensn}
environment=$work_root/env.zsh
binary=$build_dir/python/opensn
mesh_dir=${OPENSN_TUO_MESH_DIR:-$study_root/builds/gfx942/mesh-cache}
results_root=${OPENSN_TUO_RESULTS:-$study_root/results}
label=${OPENSN_TUO_LABEL:-update-3}
interactive_root=${OPENSN_TUO_INTERACTIVE_ROOT:-$results_root/$label-interactive}
batch_root=${OPENSN_TUO_BATCH_ROOT:-$results_root/$label-batch}
hardware_interactive=$interactive_root/hardware
resource_interactive=$interactive_root/resource-aware
hardware_batch=$batch_root/hardware
resource_batch=$batch_root/resource-aware
queue=${OPENSN_TUO_QUEUE:-pdebug}
interactive_time=${OPENSN_TUO_TIME_LIMIT:-60m}
interactive_iterations=${OPENSN_TUO_INTERACTIVE_ITERATIONS:-10}
batch_nodes=${OPENSN_TUO_NODES:-1,2,4,8,16,32,64,128,256}
batch_repetitions=${OPENSN_TUO_REPETITIONS:-3}
batch_iterations=${OPENSN_TUO_MAX_ITERATIONS:-10}
batch_time=${OPENSN_TUO_BATCH_TIME_LIMIT:-4h}
bank=${OPENSN_TUO_BANK:-}
worker_count=${OPENSN_CBCD_NUM_WORKERS:-}

usage()
{
  cat >&2 <<EOF
usage: $0 COMMAND [ARGS]

Commands:
  build                         fresh/resumable one-node Tuo build
  build-here                    build in the current allocation
  prepare-interactive           prepare both 1/2/4-node policy studies
  run-interactive               run both policies in one four-node allocation
  run-interactive-here          run both policies in the current allocation
  run POLICY NODES              run one policy at 1, 2, or 4 nodes
  run-here POLICY NODES         run one policy in the current allocation
  collect-interactive           collect and compare both policy studies
  prepare-batch                 prepare both strong/weak pbatch studies
  submit-batch                  submit both pbatch studies
  collect-batch                 collect and compare both pbatch studies
  paths                         print selected paths and study settings

POLICY is hardware or resource-aware. The default mesh directory reuses the
plain cube-dN.msh files produced by the older Tuo framework. Override it with
OPENSN_TUO_MESH_DIR. No mesh is generated by this helper.
EOF
  exit 2
}

check_policy()
{
  case $1 in
    hardware|resource-aware) ;;
    *) print -u2 'POLICY must be hardware or resource-aware.'; exit 2 ;;
  esac
}

check_nodes()
{
  case $1 in
    1|2|4) ;;
    *) print -u2 'NODES must be 1, 2, or 4.'; exit 2 ;;
  esac
}

check_settings()
{
  [[ $interactive_iterations == <1-> ]] || {
    print -u2 'OPENSN_TUO_INTERACTIVE_ITERATIONS must be positive.'
    exit 2
  }
  [[ $batch_repetitions == <1-> && $batch_iterations == <1-> ]] || {
    print -u2 'Batch repetitions and iterations must be positive.'
    exit 2
  }
  [[ -z $worker_count || $worker_count == <1-> ]] || {
    print -u2 'OPENSN_CBCD_NUM_WORKERS must be positive when set.'
    exit 2
  }
  [[ $queue == pdebug ]] || {
    print -u2 'Interactive commands are restricted to the pdebug queue.'
    exit 2
  }
}

require_build()
{
  [[ -r $environment && -x $binary ]] || {
    print -u2 "OpenSn is not ready under $work_root"
    print -u2 "Run '$script build' first."
    exit 1
  }
}

allocation()
{
  local nodes=$1
  local ranks=$((nodes * 4))
  local -a command=(
    flux alloc -N "$nodes" -n "$ranks" -q pdebug
    --exclusive -t "$interactive_time"
  )
  [[ -z $bank ]] || command+=(-B "$bank")
  print -r -l -- "${command[@]}"
}

build_here()
{
  : ${FLUX_JOB_ID:?build-here requires an active Flux allocation}
  if [[ -r $environment && -x $binary ]]; then
    print -- "Reusing completed build: $binary"
    return
  fi

  export OPENSN_SOURCE=$source_dir
  export OPENSN_TUO_ROOT=$work_root
  export OPENSN_TUO_BUILD=$build_dir
  mkdir -p -- "$work_root/logs"

  zsh "$source_dir/tools/scaling/tuo/bootstrap.zsh" all \
    |& tee "$work_root/logs/build.log"
}

build()
{
  if [[ -r $environment && -x $binary ]]; then
    print -- "Reusing completed build: $binary"
    return
  fi
  local -a command=("${(@f)$(allocation 1)}")
  "$command[@]" zsh "$script" build-here
}

study_for()
{
  local scope=$1
  local policy=$2
  case $scope:$policy in
    interactive:hardware) print -- "$hardware_interactive" ;;
    interactive:resource-aware) print -- "$resource_interactive" ;;
    batch:hardware) print -- "$hardware_batch" ;;
    batch:resource-aware) print -- "$resource_batch" ;;
    *) exit 2 ;;
  esac
}

prepare_one()
{
  local scope=$1
  local policy=$2
  local output=$(study_for "$scope" "$policy")
  if [[ -r $output/manifest.json ]]; then
    print -- "Reusing prepared $scope $policy study: $output"
    return
  fi

  local nodes kinds repetitions iterations study_queue time_limit
  if [[ $scope == interactive ]]; then
    nodes=1,2,4
    kinds=strong
    repetitions=1
    iterations=$interactive_iterations
    study_queue=pdebug
    time_limit=$interactive_time
  else
    nodes=$batch_nodes
    kinds=strong,weak
    repetitions=$batch_repetitions
    iterations=$batch_iterations
    study_queue=pbatch
    time_limit=$batch_time
  fi

  local -a optional_args=()
  [[ -z $bank ]] || optional_args+=(--bank "$bank")
  [[ -z $worker_count ]] || optional_args+=(--cbcd-workers "$worker_count")

  source "$environment"
  python "$source_dir/tools/scaling/tuo/study.py" prepare \
    --binary "$binary" \
    --environment "$environment" \
    --output "$output" \
    --mesh-dir "$mesh_dir" \
    --label "$label-$scope-$policy" \
    --nodes "$nodes" \
    --kinds "$kinds" \
    --repetitions "$repetitions" \
    --max-iterations "$iterations" \
    --queue "$study_queue" \
    --time-limit "$time_limit" \
    --worker-policy "$policy" \
    --no-save-angular-flux \
    "${optional_args[@]}"
}

prepare_interactive()
{
  require_build
  prepare_one interactive hardware
  prepare_one interactive resource-aware
}

run_here()
{
  local policy=$1
  local nodes=$2
  check_policy "$policy"
  check_nodes "$nodes"
  : ${FLUX_JOB_ID:?run-here requires an active Flux allocation}
  local study=$(study_for interactive "$policy")
  [[ -x $study/jobs/strong-$nodes.zsh ]] || {
    print -u2 'Run prepare-interactive first.'
    exit 1
  }
  zsh "$study/jobs/strong-$nodes.zsh"
}

run_one()
{
  local policy=$1
  local nodes=$2
  check_policy "$policy"
  check_nodes "$nodes"
  local -a command=("${(@f)$(allocation "$nodes")}")
  "$command[@]" zsh "$script" run-here "$policy" "$nodes"
}

run_interactive_here()
{
  : ${FLUX_JOB_ID:?run-interactive-here requires an active Flux allocation}
  run_here hardware 1
  run_here resource-aware 1
  run_here resource-aware 2
  run_here hardware 2
  run_here hardware 4
  run_here resource-aware 4
}

run_interactive()
{
  prepare_interactive
  local -a command=("${(@f)$(allocation 4)}")
  "$command[@]" zsh "$script" run-interactive-here
}

collect_one()
{
  local study=$1
  source "$environment"
  python "$source_dir/tools/scaling/tuo/study.py" collect --study "$study"
  sed -n '1,40p' "$study/summary.md"
}

compare_pair()
{
  local scope=$1
  local hardware=$(study_for "$scope" hardware)
  local resource=$(study_for "$scope" resource-aware)
  local output
  if [[ $scope == interactive ]]; then
    output=$interactive_root/comparison
  else
    output=$batch_root/comparison
  fi
  source "$environment"
  python "$source_dir/tools/scaling/tuo/study.py" compare \
    --baseline "$hardware" \
    --candidate "$resource" \
    --output "$output"
  sed -n '1,80p' "$output/comparison.md"
}

collect_interactive()
{
  require_build
  collect_one "$hardware_interactive"
  collect_one "$resource_interactive"
  compare_pair interactive
}

prepare_batch()
{
  require_build
  prepare_one batch hardware
  prepare_one batch resource-aware
}

submit_batch()
{
  prepare_batch
  zsh "$hardware_batch/submit.zsh"
  zsh "$resource_batch/submit.zsh"
}

collect_batch()
{
  require_build
  collect_one "$hardware_batch"
  collect_one "$resource_batch"
  compare_pair batch
}

paths()
{
  print -- "source=$source_dir"
  print -- "root=$work_root"
  print -- "environment=$environment"
  print -- "build=$build_dir"
  print -- "binary=$binary"
  print -- "meshes=$mesh_dir"
  print -- "interactive_hardware=$hardware_interactive"
  print -- "interactive_resource_aware=$resource_interactive"
  print -- "batch_hardware=$hardware_batch"
  print -- "batch_resource_aware=$resource_batch"
  print -- "interactive_iterations=$interactive_iterations"
  print -- "batch_nodes=$batch_nodes"
  print -- "batch_repetitions=$batch_repetitions"
  print -- "batch_iterations=$batch_iterations"
  print -- "fixed_workers=${worker_count:-unset}"
}

check_settings
(( $# >= 1 )) || usage
command=$1
shift
case $command in
  build) (( $# == 0 )) || usage; build ;;
  build-here) (( $# == 0 )) || usage; build_here ;;
  prepare-interactive) (( $# == 0 )) || usage; prepare_interactive ;;
  run-interactive) (( $# == 0 )) || usage; run_interactive ;;
  run-interactive-here) (( $# == 0 )) || usage; run_interactive_here ;;
  run) (( $# == 2 )) || usage; run_one "$1" "$2" ;;
  run-here) (( $# == 2 )) || usage; run_here "$1" "$2" ;;
  collect-interactive) (( $# == 0 )) || usage; collect_interactive ;;
  prepare-batch) (( $# == 0 )) || usage; prepare_batch ;;
  submit-batch) (( $# == 0 )) || usage; submit_batch ;;
  collect-batch) (( $# == 0 )) || usage; collect_batch ;;
  paths) (( $# == 0 )) || usage; paths ;;
  *) usage ;;
esac
